apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-concerns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: autlog-kom
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
  destination:
      server: https://kubernetes.default.svc
      namespace: autlog-kom
  source:
    repoURL: git@github.com:ORG/REPO.git
    targetRevision: main
    path: charts/common-concerns
    helm:
      valueFiles:
        - values.yaml
        - ../../billund/values.yaml