{{ if .Values.service.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{.Values.service.name}}-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: novus-runtime
  data:
{{- range $i, $value := .Values.service.secrets }}
{{- range $value.SecretStoreKeys}}
    - secretKey: {{ . }} # Secret key to be created in the new secret defined in spec.target.name.   
      remoteRef:
        key: {{ $value.SecretStoreName }} # Name of the secret in AWS Secrets Manager
        property: {{ . }} # Secret key of secret in AWS Secrets Manager
{{- end}}
  target:
    name: {{ $value.k8secretName }} # Name of the secret that will be created in your runtime
{{- end}}
{{ end }}