apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service.name }}
  ports:
    {{- range $port := .Values.service.container.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
    {{- end }}
