service:
  azure:
    clientId:
      name: AzureAd__ClientId
      value: value
  secrets:
    - k8secretName: secrets
      SecretStoreName: runtimes/test-runtime/secrets
      SecretStoreKeys:
        - AzureAd__ClientSecret
  envVars:
    - name: SomeFeatureToggle
      value: "true"
